/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BetaRouteImport } from './routes/beta'
import { Route as DecksRouteImport } from './routes/decks'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LeaderboardsRouteImport } from './routes/leaderboards'
import { Route as MetaRouteImport } from './routes/meta'
import { Route as NewsRouteImport } from './routes/news'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TournamentsRouteImport } from './routes/tournaments'
import { Route as CardsIndexRouteImport } from './routes/cards/index'
import { Route as CardsSlugRouteImport } from './routes/cards/$slug'
import { Route as ClansTagRouteImport } from './routes/clans/$tag'
import { Route as ClansSearchRouteImport } from './routes/clans/search'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as GuidesSlugRouteImport } from './routes/guides/$slug'
import { Route as PlayersIndexRouteImport } from './routes/players/index'
import { Route as PlayersTagRouteImport } from './routes/players/$tag'
import { Route as PlayersCompareRouteImport } from './routes/players/compare'
import { Route as ClansTagWarRouteImport } from './routes/clans/$tag_.war'
import { Route as ClansTagManageRouteImport } from './routes/clans/$tag_.manage'
import { Route as PlayersTagUpgradesRouteImport } from './routes/players/$tag_.upgrades'
import { Route as PlayersTagHistoryRouteImport } from './routes/players/$tag_.history'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BetaRoute = BetaRouteImport.update({
  id: '/beta',
  path: '/beta',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksRoute = DecksRouteImport.update({
  id: '/decks',
  path: '/decks',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardsRoute = LeaderboardsRouteImport.update({
  id: '/leaderboards',
  path: '/leaderboards',
  getParentRoute: () => rootRouteImport,
} as any)
const MetaRoute = MetaRouteImport.update({
  id: '/meta',
  path: '/meta',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsRoute = TournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsIndexRoute = CardsIndexRouteImport.update({
  id: '/cards/',
  path: '/cards/',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsSlugRoute = CardsSlugRouteImport.update({
  id: '/cards/$slug',
  path: '/cards/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ClansTagRoute = ClansTagRouteImport.update({
  id: '/clans/$tag',
  path: '/clans/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const ClansSearchRoute = ClansSearchRouteImport.update({
  id: '/clans/search',
  path: '/clans/search',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersIndexRoute = PlayersIndexRouteImport.update({
  id: '/players/',
  path: '/players/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersTagRoute = PlayersTagRouteImport.update({
  id: '/players/$tag',
  path: '/players/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersCompareRoute = PlayersCompareRouteImport.update({
  id: '/players/compare',
  path: '/players/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ClansTagWarRoute = ClansTagWarRouteImport.update({
  id: '/clans/$tag_/war',
  path: '/clans/$tag/war',
  getParentRoute: () => rootRouteImport,
} as any)
const ClansTagManageRoute = ClansTagManageRouteImport.update({
  id: '/clans/$tag_/manage',
  path: '/clans/$tag/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersTagUpgradesRoute = PlayersTagUpgradesRouteImport.update({
  id: '/players/$tag_/upgrades',
  path: '/players/$tag/upgrades',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersTagHistoryRoute = PlayersTagHistoryRouteImport.update({
  id: '/players/$tag_/history',
  path: '/players/$tag/history',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/beta': typeof BetaRoute
  '/decks': typeof DecksRoute
  '/history': typeof HistoryRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/meta': typeof MetaRoute
  '/news': typeof NewsRoute
  '/tools': typeof ToolsRoute
  '/tournaments': typeof TournamentsRoute
  '/cards/$slug': typeof CardsSlugRoute
  '/clans/$tag': typeof ClansTagRoute
  '/clans/search': typeof ClansSearchRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/players/$tag': typeof PlayersTagRoute
  '/players/compare': typeof PlayersCompareRoute
  '/cards/': typeof CardsIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/players/': typeof PlayersIndexRoute
  '/clans/$tag/war': typeof ClansTagWarRoute
  '/clans/$tag/manage': typeof ClansTagManageRoute
  '/players/$tag/upgrades': typeof PlayersTagUpgradesRoute
  '/players/$tag/history': typeof PlayersTagHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/beta': typeof BetaRoute
  '/decks': typeof DecksRoute
  '/history': typeof HistoryRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/meta': typeof MetaRoute
  '/news': typeof NewsRoute
  '/tools': typeof ToolsRoute
  '/tournaments': typeof TournamentsRoute
  '/cards/$slug': typeof CardsSlugRoute
  '/clans/$tag': typeof ClansTagRoute
  '/clans/search': typeof ClansSearchRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/players/$tag': typeof PlayersTagRoute
  '/players/compare': typeof PlayersCompareRoute
  '/cards': typeof CardsIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/players': typeof PlayersIndexRoute
  '/clans/$tag/war': typeof ClansTagWarRoute
  '/clans/$tag/manage': typeof ClansTagManageRoute
  '/players/$tag/upgrades': typeof PlayersTagUpgradesRoute
  '/players/$tag/history': typeof PlayersTagHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/beta': typeof BetaRoute
  '/decks': typeof DecksRoute
  '/history': typeof HistoryRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/meta': typeof MetaRoute
  '/news': typeof NewsRoute
  '/tools': typeof ToolsRoute
  '/tournaments': typeof TournamentsRoute
  '/cards/$slug': typeof CardsSlugRoute
  '/clans/$tag': typeof ClansTagRoute
  '/clans/search': typeof ClansSearchRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/players/$tag': typeof PlayersTagRoute
  '/players/compare': typeof PlayersCompareRoute
  '/cards/': typeof CardsIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/players/': typeof PlayersIndexRoute
  '/clans/$tag_/war': typeof ClansTagWarRoute
  '/clans/$tag_/manage': typeof ClansTagManageRoute
  '/players/$tag_/upgrades': typeof PlayersTagUpgradesRoute
  '/players/$tag_/history': typeof PlayersTagHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/beta'
    | '/decks'
    | '/history'
    | '/leaderboards'
    | '/meta'
    | '/news'
    | '/tools'
    | '/tournaments'
    | '/cards/$slug'
    | '/clans/$tag'
    | '/clans/search'
    | '/guides/$slug'
    | '/players/$tag'
    | '/players/compare'
    | '/cards/'
    | '/guides/'
    | '/players/'
    | '/clans/$tag/war'
    | '/clans/$tag/manage'
    | '/players/$tag/upgrades'
    | '/players/$tag/history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/beta'
    | '/decks'
    | '/history'
    | '/leaderboards'
    | '/meta'
    | '/news'
    | '/tools'
    | '/tournaments'
    | '/cards/$slug'
    | '/clans/$tag'
    | '/clans/search'
    | '/guides/$slug'
    | '/players/$tag'
    | '/players/compare'
    | '/cards'
    | '/guides'
    | '/players'
    | '/clans/$tag/war'
    | '/clans/$tag/manage'
    | '/players/$tag/upgrades'
    | '/players/$tag/history'
  id:
    | '__root__'
    | '/'
    | '/beta'
    | '/decks'
    | '/history'
    | '/leaderboards'
    | '/meta'
    | '/news'
    | '/tools'
    | '/tournaments'
    | '/cards/$slug'
    | '/clans/$tag'
    | '/clans/search'
    | '/guides/$slug'
    | '/players/$tag'
    | '/players/compare'
    | '/cards/'
    | '/guides/'
    | '/players/'
    | '/clans/$tag_/war'
    | '/clans/$tag_/manage'
    | '/players/$tag_/upgrades'
    | '/players/$tag_/history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BetaRoute: typeof BetaRoute
  DecksRoute: typeof DecksRoute
  HistoryRoute: typeof HistoryRoute
  LeaderboardsRoute: typeof LeaderboardsRoute
  MetaRoute: typeof MetaRoute
  NewsRoute: typeof NewsRoute
  ToolsRoute: typeof ToolsRoute
  TournamentsRoute: typeof TournamentsRoute
  CardsSlugRoute: typeof CardsSlugRoute
  ClansTagRoute: typeof ClansTagRoute
  ClansSearchRoute: typeof ClansSearchRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  PlayersTagRoute: typeof PlayersTagRoute
  PlayersCompareRoute: typeof PlayersCompareRoute
  CardsIndexRoute: typeof CardsIndexRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  PlayersIndexRoute: typeof PlayersIndexRoute
  ClansTagWarRoute: typeof ClansTagWarRoute
  ClansTagManageRoute: typeof ClansTagManageRoute
  PlayersTagUpgradesRoute: typeof PlayersTagUpgradesRoute
  PlayersTagHistoryRoute: typeof PlayersTagHistoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beta': {
      id: '/beta'
      path: '/beta'
      fullPath: '/beta'
      preLoaderRoute: typeof BetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks': {
      id: '/decks'
      path: '/decks'
      fullPath: '/decks'
      preLoaderRoute: typeof DecksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboards': {
      id: '/leaderboards'
      path: '/leaderboards'
      fullPath: '/leaderboards'
      preLoaderRoute: typeof LeaderboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meta': {
      id: '/meta'
      path: '/meta'
      fullPath: '/meta'
      preLoaderRoute: typeof MetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments': {
      id: '/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards/': {
      id: '/cards/'
      path: '/cards'
      fullPath: '/cards/'
      preLoaderRoute: typeof CardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards/$slug': {
      id: '/cards/$slug'
      path: '/cards/$slug'
      fullPath: '/cards/$slug'
      preLoaderRoute: typeof CardsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clans/$tag': {
      id: '/clans/$tag'
      path: '/clans/$tag'
      fullPath: '/clans/$tag'
      preLoaderRoute: typeof ClansTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clans/search': {
      id: '/clans/search'
      path: '/clans/search'
      fullPath: '/clans/search'
      preLoaderRoute: typeof ClansSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/': {
      id: '/players/'
      path: '/players'
      fullPath: '/players/'
      preLoaderRoute: typeof PlayersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$tag': {
      id: '/players/$tag'
      path: '/players/$tag'
      fullPath: '/players/$tag'
      preLoaderRoute: typeof PlayersTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/compare': {
      id: '/players/compare'
      path: '/players/compare'
      fullPath: '/players/compare'
      preLoaderRoute: typeof PlayersCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clans/$tag_/war': {
      id: '/clans/$tag_/war'
      path: '/clans/$tag/war'
      fullPath: '/clans/$tag/war'
      preLoaderRoute: typeof ClansTagWarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clans/$tag_/manage': {
      id: '/clans/$tag_/manage'
      path: '/clans/$tag/manage'
      fullPath: '/clans/$tag/manage'
      preLoaderRoute: typeof ClansTagManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$tag_/upgrades': {
      id: '/players/$tag_/upgrades'
      path: '/players/$tag/upgrades'
      fullPath: '/players/$tag/upgrades'
      preLoaderRoute: typeof PlayersTagUpgradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$tag_/history': {
      id: '/players/$tag_/history'
      path: '/players/$tag/history'
      fullPath: '/players/$tag/history'
      preLoaderRoute: typeof PlayersTagHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BetaRoute: BetaRoute,
  DecksRoute: DecksRoute,
  HistoryRoute: HistoryRoute,
  LeaderboardsRoute: LeaderboardsRoute,
  MetaRoute: MetaRoute,
  NewsRoute: NewsRoute,
  ToolsRoute: ToolsRoute,
  TournamentsRoute: TournamentsRoute,
  CardsSlugRoute: CardsSlugRoute,
  ClansTagRoute: ClansTagRoute,
  ClansSearchRoute: ClansSearchRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  PlayersTagRoute: PlayersTagRoute,
  PlayersCompareRoute: PlayersCompareRoute,
  CardsIndexRoute: CardsIndexRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  PlayersIndexRoute: PlayersIndexRoute,
  ClansTagWarRoute: ClansTagWarRoute,
  ClansTagManageRoute: ClansTagManageRoute,
  PlayersTagUpgradesRoute: PlayersTagUpgradesRoute,
  PlayersTagHistoryRoute: PlayersTagHistoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
