/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BetaRouteImport } from './routes/beta'
import { Route as DecksRouteImport } from './routes/decks'
import { Route as LeaderboardsRouteImport } from './routes/leaderboards'
import { Route as MetaRouteImport } from './routes/meta'
import { Route as TournamentsRouteImport } from './routes/tournaments'
import { Route as CardsIndexRouteImport } from './routes/cards/index'
import { Route as CardsSlugRouteImport } from './routes/cards/$slug'
import { Route as ClansTagRouteImport } from './routes/clans/$tag'
import { Route as ClansSearchRouteImport } from './routes/clans/search'
import { Route as PlayersIndexRouteImport } from './routes/players/index'
import { Route as PlayersTagRouteImport } from './routes/players/$tag'
import { Route as PlayersCompareRouteImport } from './routes/players/compare'
import { Route as ClansTagWarRouteImport } from './routes/clans/$tag_.war'
import { Route as ClansTagManageRouteImport } from './routes/clans/$tag_.manage'
import { Route as PlayersTagUpgradesRouteImport } from './routes/players/$tag_.upgrades'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BetaRoute = BetaRouteImport.update({
  id: '/beta',
  path: '/beta',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksRoute = DecksRouteImport.update({
  id: '/decks',
  path: '/decks',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardsRoute = LeaderboardsRouteImport.update({
  id: '/leaderboards',
  path: '/leaderboards',
  getParentRoute: () => rootRouteImport,
} as any)
const MetaRoute = MetaRouteImport.update({
  id: '/meta',
  path: '/meta',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsRoute = TournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsIndexRoute = CardsIndexRouteImport.update({
  id: '/cards/',
  path: '/cards/',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsSlugRoute = CardsSlugRouteImport.update({
  id: '/cards/$slug',
  path: '/cards/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ClansTagRoute = ClansTagRouteImport.update({
  id: '/clans/$tag',
  path: '/clans/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const ClansSearchRoute = ClansSearchRouteImport.update({
  id: '/clans/search',
  path: '/clans/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersIndexRoute = PlayersIndexRouteImport.update({
  id: '/players/',
  path: '/players/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersTagRoute = PlayersTagRouteImport.update({
  id: '/players/$tag',
  path: '/players/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersCompareRoute = PlayersCompareRouteImport.update({
  id: '/players/compare',
  path: '/players/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ClansTagWarRoute = ClansTagWarRouteImport.update({
  id: '/clans/$tag_/war',
  path: '/clans/$tag/war',
  getParentRoute: () => rootRouteImport,
} as any)
const ClansTagManageRoute = ClansTagManageRouteImport.update({
  id: '/clans/$tag_/manage',
  path: '/clans/$tag/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersTagUpgradesRoute = PlayersTagUpgradesRouteImport.update({
  id: '/players/$tag_/upgrades',
  path: '/players/$tag/upgrades',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/beta': typeof BetaRoute
  '/decks': typeof DecksRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/meta': typeof MetaRoute
  '/tournaments': typeof TournamentsRoute
  '/cards/$slug': typeof CardsSlugRoute
  '/clans/$tag': typeof ClansTagRoute
  '/clans/search': typeof ClansSearchRoute
  '/players/$tag': typeof PlayersTagRoute
  '/players/compare': typeof PlayersCompareRoute
  '/cards/': typeof CardsIndexRoute
  '/players/': typeof PlayersIndexRoute
  '/clans/$tag/war': typeof ClansTagWarRoute
  '/clans/$tag/manage': typeof ClansTagManageRoute
  '/players/$tag/upgrades': typeof PlayersTagUpgradesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/beta': typeof BetaRoute
  '/decks': typeof DecksRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/meta': typeof MetaRoute
  '/tournaments': typeof TournamentsRoute
  '/cards/$slug': typeof CardsSlugRoute
  '/clans/$tag': typeof ClansTagRoute
  '/clans/search': typeof ClansSearchRoute
  '/players/$tag': typeof PlayersTagRoute
  '/players/compare': typeof PlayersCompareRoute
  '/cards': typeof CardsIndexRoute
  '/players': typeof PlayersIndexRoute
  '/clans/$tag/war': typeof ClansTagWarRoute
  '/clans/$tag/manage': typeof ClansTagManageRoute
  '/players/$tag/upgrades': typeof PlayersTagUpgradesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/beta': typeof BetaRoute
  '/decks': typeof DecksRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/meta': typeof MetaRoute
  '/tournaments': typeof TournamentsRoute
  '/cards/$slug': typeof CardsSlugRoute
  '/clans/$tag': typeof ClansTagRoute
  '/clans/search': typeof ClansSearchRoute
  '/players/$tag': typeof PlayersTagRoute
  '/players/compare': typeof PlayersCompareRoute
  '/cards/': typeof CardsIndexRoute
  '/players/': typeof PlayersIndexRoute
  '/clans/$tag_/war': typeof ClansTagWarRoute
  '/clans/$tag_/manage': typeof ClansTagManageRoute
  '/players/$tag_/upgrades': typeof PlayersTagUpgradesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/beta'
    | '/decks'
    | '/leaderboards'
    | '/meta'
    | '/tournaments'
    | '/cards/$slug'
    | '/clans/$tag'
    | '/clans/search'
    | '/players/$tag'
    | '/players/compare'
    | '/cards/'
    | '/players/'
    | '/clans/$tag/war'
    | '/clans/$tag/manage'
    | '/players/$tag/upgrades'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/beta'
    | '/decks'
    | '/leaderboards'
    | '/meta'
    | '/tournaments'
    | '/cards/$slug'
    | '/clans/$tag'
    | '/clans/search'
    | '/players/$tag'
    | '/players/compare'
    | '/cards'
    | '/players'
    | '/clans/$tag/war'
    | '/clans/$tag/manage'
    | '/players/$tag/upgrades'
  id:
    | '__root__'
    | '/'
    | '/beta'
    | '/decks'
    | '/leaderboards'
    | '/meta'
    | '/tournaments'
    | '/cards/$slug'
    | '/clans/$tag'
    | '/clans/search'
    | '/players/$tag'
    | '/players/compare'
    | '/cards/'
    | '/players/'
    | '/clans/$tag_/war'
    | '/clans/$tag_/manage'
    | '/players/$tag_/upgrades'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BetaRoute: typeof BetaRoute
  DecksRoute: typeof DecksRoute
  LeaderboardsRoute: typeof LeaderboardsRoute
  MetaRoute: typeof MetaRoute
  TournamentsRoute: typeof TournamentsRoute
  CardsSlugRoute: typeof CardsSlugRoute
  ClansTagRoute: typeof ClansTagRoute
  ClansSearchRoute: typeof ClansSearchRoute
  PlayersTagRoute: typeof PlayersTagRoute
  PlayersCompareRoute: typeof PlayersCompareRoute
  CardsIndexRoute: typeof CardsIndexRoute
  PlayersIndexRoute: typeof PlayersIndexRoute
  ClansTagWarRoute: typeof ClansTagWarRoute
  ClansTagManageRoute: typeof ClansTagManageRoute
  PlayersTagUpgradesRoute: typeof PlayersTagUpgradesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beta': {
      id: '/beta'
      path: '/beta'
      fullPath: '/beta'
      preLoaderRoute: typeof BetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks': {
      id: '/decks'
      path: '/decks'
      fullPath: '/decks'
      preLoaderRoute: typeof DecksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboards': {
      id: '/leaderboards'
      path: '/leaderboards'
      fullPath: '/leaderboards'
      preLoaderRoute: typeof LeaderboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meta': {
      id: '/meta'
      path: '/meta'
      fullPath: '/meta'
      preLoaderRoute: typeof MetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments': {
      id: '/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards/': {
      id: '/cards/'
      path: '/cards'
      fullPath: '/cards/'
      preLoaderRoute: typeof CardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards/$slug': {
      id: '/cards/$slug'
      path: '/cards/$slug'
      fullPath: '/cards/$slug'
      preLoaderRoute: typeof CardsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clans/$tag': {
      id: '/clans/$tag'
      path: '/clans/$tag'
      fullPath: '/clans/$tag'
      preLoaderRoute: typeof ClansTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clans/search': {
      id: '/clans/search'
      path: '/clans/search'
      fullPath: '/clans/search'
      preLoaderRoute: typeof ClansSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/': {
      id: '/players/'
      path: '/players'
      fullPath: '/players/'
      preLoaderRoute: typeof PlayersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$tag': {
      id: '/players/$tag'
      path: '/players/$tag'
      fullPath: '/players/$tag'
      preLoaderRoute: typeof PlayersTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/compare': {
      id: '/players/compare'
      path: '/players/compare'
      fullPath: '/players/compare'
      preLoaderRoute: typeof PlayersCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clans/$tag_/war': {
      id: '/clans/$tag_/war'
      path: '/clans/$tag/war'
      fullPath: '/clans/$tag/war'
      preLoaderRoute: typeof ClansTagWarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clans/$tag_/manage': {
      id: '/clans/$tag_/manage'
      path: '/clans/$tag/manage'
      fullPath: '/clans/$tag/manage'
      preLoaderRoute: typeof ClansTagManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$tag_/upgrades': {
      id: '/players/$tag_/upgrades'
      path: '/players/$tag/upgrades'
      fullPath: '/players/$tag/upgrades'
      preLoaderRoute: typeof PlayersTagUpgradesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BetaRoute: BetaRoute,
  DecksRoute: DecksRoute,
  LeaderboardsRoute: LeaderboardsRoute,
  MetaRoute: MetaRoute,
  TournamentsRoute: TournamentsRoute,
  CardsSlugRoute: CardsSlugRoute,
  ClansTagRoute: ClansTagRoute,
  ClansSearchRoute: ClansSearchRoute,
  PlayersTagRoute: PlayersTagRoute,
  PlayersCompareRoute: PlayersCompareRoute,
  CardsIndexRoute: CardsIndexRoute,
  PlayersIndexRoute: PlayersIndexRoute,
  ClansTagWarRoute: ClansTagWarRoute,
  ClansTagManageRoute: ClansTagManageRoute,
  PlayersTagUpgradesRoute: PlayersTagUpgradesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
