/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as ConnectIndexRouteImport } from './routes/connect/index'
import { Route as ConnectGameRouteImport } from './routes/connect/$game'
import { Route as LaunchGameRouteImport } from './routes/launch/$game'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsConnectionsRouteImport } from './routes/settings/connections'
import { Route as GamesGameIndexRouteImport } from './routes/games/$game/index'
import { Route as GamesGameTagRouteImport } from './routes/games/$game/$tag'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectIndexRoute = ConnectIndexRouteImport.update({
  id: '/connect/',
  path: '/connect/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectGameRoute = ConnectGameRouteImport.update({
  id: '/connect/$game',
  path: '/connect/$game',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchGameRoute = LaunchGameRouteImport.update({
  id: '/launch/$game',
  path: '/launch/$game',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsConnectionsRoute = SettingsConnectionsRouteImport.update({
  id: '/settings/connections',
  path: '/settings/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameIndexRoute = GamesGameIndexRouteImport.update({
  id: '/games/$game/',
  path: '/games/$game/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameTagRoute = GamesGameTagRouteImport.update({
  id: '/games/$game/$tag',
  path: '/games/$game/$tag',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/connect/$game': typeof ConnectGameRoute
  '/launch/$game': typeof LaunchGameRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/connect/': typeof ConnectIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/games/$game/$tag': typeof GamesGameTagRoute
  '/games/$game/': typeof GamesGameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/connect/$game': typeof ConnectGameRoute
  '/launch/$game': typeof LaunchGameRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/connect': typeof ConnectIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/games/$game/$tag': typeof GamesGameTagRoute
  '/games/$game': typeof GamesGameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/connect/$game': typeof ConnectGameRoute
  '/launch/$game': typeof LaunchGameRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/connect/': typeof ConnectIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/games/$game/$tag': typeof GamesGameTagRoute
  '/games/$game/': typeof GamesGameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/connect/$game'
    | '/launch/$game'
    | '/settings/connections'
    | '/connect/'
    | '/settings/'
    | '/games/$game/$tag'
    | '/games/$game/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/connect/$game'
    | '/launch/$game'
    | '/settings/connections'
    | '/connect'
    | '/settings'
    | '/games/$game/$tag'
    | '/games/$game'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/connect/$game'
    | '/launch/$game'
    | '/settings/connections'
    | '/connect/'
    | '/settings/'
    | '/games/$game/$tag'
    | '/games/$game/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ConnectGameRoute: typeof ConnectGameRoute
  LaunchGameRoute: typeof LaunchGameRoute
  SettingsConnectionsRoute: typeof SettingsConnectionsRoute
  ConnectIndexRoute: typeof ConnectIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  GamesGameTagRoute: typeof GamesGameTagRoute
  GamesGameIndexRoute: typeof GamesGameIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/': {
      id: '/connect/'
      path: '/connect'
      fullPath: '/connect/'
      preLoaderRoute: typeof ConnectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/$game': {
      id: '/connect/$game'
      path: '/connect/$game'
      fullPath: '/connect/$game'
      preLoaderRoute: typeof ConnectGameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch/$game': {
      id: '/launch/$game'
      path: '/launch/$game'
      fullPath: '/launch/$game'
      preLoaderRoute: typeof LaunchGameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/connections': {
      id: '/settings/connections'
      path: '/settings/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof SettingsConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$game/': {
      id: '/games/$game/'
      path: '/games/$game'
      fullPath: '/games/$game/'
      preLoaderRoute: typeof GamesGameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$game/$tag': {
      id: '/games/$game/$tag'
      path: '/games/$game/$tag'
      fullPath: '/games/$game/$tag'
      preLoaderRoute: typeof GamesGameTagRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ConnectGameRoute: ConnectGameRoute,
  LaunchGameRoute: LaunchGameRoute,
  SettingsConnectionsRoute: SettingsConnectionsRoute,
  ConnectIndexRoute: ConnectIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  GamesGameTagRoute: GamesGameTagRoute,
  GamesGameIndexRoute: GamesGameIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
