import { useMemo } from "react";
import type { MetaMode } from "@/lib/clash/battles";
import { useI18n } from "@/lib/i18n";
import {
  formatCount,
  formatPercent,
  formatPoints,
  type DeckSort,
  type MetaView,
  type MetaWindow,
  type Quadrant,
  type ReportLocale
} from "@/lib/metaReport";

/** Every string the meta report renders, in English and Spanish. */
const en = {
  heroDek: "What's strong, what to play, and what's changing, counted from real battle logs rather than opinion.",
  heroSampleLoading: "Counting observed decks…",
  loading: "Loading",
  decksObserved: (count: string) => `${count} decks observed`,
  updated: (age: string) => `updated ${age}`,
  windowLabel: (days: MetaWindow): string => (days === 1 ? "Last 24 hours" : "Last 7 days"),
  windowShort: (days: MetaWindow): string => (days === 1 ? "24h" : "7 days"),
  controlsLabel: "Meta report controls",
  modeGroup: "Battle mode",
  windowGroup: "Time window",
  viewGroup: "Report view",
  views: { overview: "Overview", decks: "Decks", cards: "Cards", archetypes: "Archetypes" } satisfies Record<MetaView, string>,
  modes: {
    ladder: "Trophy Road",
    pathOfLegends: "Path of Legends",
    challenge: "Challenges",
    tournament: "Tournaments",
    clanWar: "Clan Wars"
  } satisfies Record<MetaMode, string>,

  // Overview
  pulseTitle: "Meta pulse",
  pulseMostPlayed: "Most-played deck",
  pulseBestRated: "Best-rated deck",
  pulseStrongest: "Strongest card",
  pulseRising: "Rising card",
  pulseHottest: "Hottest archetype",
  pulseNoData: "Not enough games yet",
  ofGames: (value: string) => `${value} of games`,
  ratingValue: (value: string) => `Rating ${value}`,
  winsOver: (rate: string, games: string) => `${rate} wins over ${games} games`,
  tierWins: (tier: string, rate: string) => `${tier} tier, ${rate} win rate`,
  usagePoints: (points: string) => `${points} usage pts`,
  winPoints: (points: string) => `${points} win-rate pts`,
  summaryTitle: (mode: string, days: MetaWindow) => (days === 1 ? `${mode} today` : `${mode} this week`),
  topDecksTitle: "Top decks right now",
  topDecksNote: "Ranked by rating: a conservative win rate that discounts small samples, plus a little popularity.",
  seeAllDecks: "See all decks",
  tierStripTitle: "Card tiers",
  fullTierList: "Full tier list and meta map",
  moversTitle: "Movers",
  rising: "Rising",
  falling: "Falling",
  archetypesTitle: "Leading archetypes",
  allArchetypes: "All archetypes",

  // Decks
  sortGroup: "Sort decks",
  sorts: { rating: "Best rated", popularity: "Most played", winRate: "Highest win rate" } satisfies Record<DeckSort, string>,
  popularCards: "Popular cards",
  requireCard: (name: string) => `Require ${name}`,
  filterSearch: "Find a card",
  filterSearchPlaceholder: "Search any card…",
  filterRequire: "Require",
  filterExclude: "Exclude",
  filterModeGroup: "Filter type",
  noCardMatches: "No card matches that name.",
  withCard: (name: string) => `With ${name}`,
  withoutCard: (name: string) => `Without ${name}`,
  removeFilter: (label: string) => `Remove filter: ${label}`,
  clearFilters: "Clear filters",
  resultCount: (matched: string, total: string) => `${matched} of ${total} ranked decks`,
  advancedSearch: "Advanced search with trophy bands and war sets",
  showMore: "Show more decks",
  noDecksMatch: "No ranked deck contains every card you required.",
  noDecksMatchHint: "Remove a filter, or switch to the 7-day window for a bigger sample.",
  filterLimit: "A deck holds eight cards, so you can require at most eight.",

  // Deck tile
  rank: (value: number) => `#${value}`,
  ratingTitle: "Rating out of 100: the 95% Wilson lower bound of win rate (80%) plus relative popularity (20%).",
  winRate: "Win rate",
  games: "Games",
  usage: "Usage",
  elixir: "Avg elixir",
  evolutions: "Evolutions",
  copyToGame: "Copy to Clash Royale",
  copyLink: "Copy deck link",
  linkCopied: "Deck link copied",
  copyFailed: "Copying was blocked; use Copy to Clash Royale instead",
  openBuilder: "Open in deck builder",
  builderShort: "Builder",
  matchups: "Matchups",
  hideMatchups: "Hide matchups",
  deckLabel: (rank: number) => `Deck ranked ${rank}`,
  bestMatchups: "Best against",
  worstMatchups: "Worst against",
  matchupsLoading: "Loading matchups…",
  matchupsNote: (days: number, minimum: number) => `All tracked modes, last ${days} days, opponents with ${minimum}+ games.`,
  matchupsEmpty: (minimum: number) => `No opponent deck has ${minimum} games against this list yet.`,
  matchupGames: (games: string) => `${games} games`,
  opponentDeck: "Opponent deck",

  // Cards
  mapTitle: "Meta map",
  mapDek: "Every card with enough games, placed by how often it is played and how often it wins.",
  mapArt: "Card art",
  mapDots: "Dots",
  mapDisplay: "Point style",
  mapX: "Usage rate",
  mapY: "Win rate",
  mapHint: "Select a card to open its full report.",
  quadrants: {
    staple: "Meta staples",
    gem: "Hidden gems",
    overplayed: "Overplayed",
    struggling: "Struggling"
  } satisfies Record<Quadrant, string>,
  quadrantHelp: {
    staple: "Popular and winning",
    gem: "Below-median usage, still winning",
    overplayed: "Popular but losing",
    struggling: "Rarely played and losing"
  } satisfies Record<Quadrant, string>,
  quadrantEmpty: "No card here.",
  mapNote: (median: string) => `Usage split at the median (${median}); win rate split at 50%.`,
  tierListTitle: "Tier list",
  tierEmpty: "No card in this tier.",
  tierLabel: (tier: string) => `${tier} tier`,
  towerTitle: "Tower Troops",
  towerStarting: "Tower Troop tracking just started, and there is no older history to backfill. Rankings appear as battles accumulate.",
  towerNote: (count: string) => `${count} decks with a recorded Tower Troop.`,
  cardLibrary: "Open the full card library",
  cardTooltipGames: (games: string) => `${games} games`,

  // Archetypes
  archetypeUsage: "of games",
  archetypeWins: "wins",
  vsPrevious: (points: string, days: MetaWindow) => `${points} pts vs previous ${days === 1 ? "day" : "week"}`,
  changeLabel: (days: MetaWindow): string => (days === 1 ? "Change vs previous day" : "Change vs previous week"),
  pointsValue: (points: string) => `${points} pts`,
  archetypeOpen: "Open archetype",
  archetypeBack: "All archetypes",
  archetypeMissing: "That archetype is not in this mode and window. Pick one below.",
  archetypeDetailDek: (name: string, games: string) => `Decks whose two most distinctive cards are ${name}. ${games} games in this window.`,
  archetypeDecks: "Most-played lists in this archetype",
  trendUsage: "Usage",
  trendWinRate: "Win rate",
  trendMetric: "Trend metric",
  archetypesEmpty: "No archetype clears the sample floor for this mode and window yet.",

  // Notes and states
  aboutData: "About this data",
  emptyDecks: "Not enough observed games in this mode and window to rank decks.",
  emptyHint: "Try the 7-day window or Path of Legends, where the sample is deepest.",
  emptyCards: "No card clears the sample floor for this mode and window.",
  emptyMovers: "No card cleared the sample floor in both windows.",
  truncated: "Some days hit the per-day read cap, so these rankings describe a bounded sample.",
  deckNote: (total: number) => `Only decks seen at least five times are ranked; this board holds the top ${total}.`,
  tierNote: (floor: string) => `Cards need ${floor}+ games. Tiers split the Wilson-ranked list: top 10% S, next 20% A, next 40% B, rest C.`,
  moverNote: (floor: string, days: MetaWindow) => `Usage change vs the previous ${days === 1 ? "day" : "week"}; cards need ${floor}+ games in both.`,
  archetypeNote: (floor: string) => `An archetype is the pair of least-common cards in a deck, grouped automatically. Families need ${floor}+ games.`,
  sourceNote: "Supercell does not publish meta statistics. StatsConnect counts crawled battle logs and always shows the sample."
};

type MetaCopy = typeof en;

const es: MetaCopy = {
  heroDek: "Qué es fuerte, qué jugar y qué está cambiando, contado a partir de registros de batalla reales y no de opiniones.",
  heroSampleLoading: "Contando mazos observados…",
  loading: "Cargando",
  decksObserved: (count) => `${count} mazos observados`,
  updated: (age) => `actualizado ${age}`,
  windowLabel: (days) => (days === 1 ? "Últimas 24 horas" : "Últimos 7 días"),
  windowShort: (days) => (days === 1 ? "24 h" : "7 días"),
  controlsLabel: "Controles del informe del meta",
  modeGroup: "Modo de batalla",
  windowGroup: "Periodo",
  viewGroup: "Vista del informe",
  views: { overview: "Resumen", decks: "Mazos", cards: "Cartas", archetypes: "Arquetipos" },
  modes: {
    ladder: "Camino de Trofeos",
    pathOfLegends: "Camino de Leyendas",
    challenge: "Desafíos",
    tournament: "Torneos",
    clanWar: "Guerras de clanes"
  },

  pulseTitle: "Pulso del meta",
  pulseMostPlayed: "Mazo más jugado",
  pulseBestRated: "Mazo mejor valorado",
  pulseStrongest: "Carta más fuerte",
  pulseRising: "Carta en alza",
  pulseHottest: "Arquetipo en auge",
  pulseNoData: "Aún no hay suficientes partidas",
  ofGames: (value) => `${value} de las partidas`,
  ratingValue: (value) => `Valoración ${value}`,
  winsOver: (rate, games) => `${rate} de victorias en ${games} partidas`,
  tierWins: (tier, rate) => `Nivel ${tier}, ${rate} de victorias`,
  usagePoints: (points) => `${points} pts de uso`,
  winPoints: (points) => `${points} pts de victorias`,
  summaryTitle: (mode, days) => (days === 1 ? `${mode} hoy` : `${mode} esta semana`),
  topDecksTitle: "Los mejores mazos ahora",
  topDecksNote: "Ordenados por valoración: un porcentaje de victorias conservador que descuenta muestras pequeñas, más algo de popularidad.",
  seeAllDecks: "Ver todos los mazos",
  tierStripTitle: "Niveles de cartas",
  fullTierList: "Lista completa y mapa del meta",
  moversTitle: "Cambios",
  rising: "Suben",
  falling: "Bajan",
  archetypesTitle: "Arquetipos principales",
  allArchetypes: "Todos los arquetipos",

  sortGroup: "Ordenar mazos",
  sorts: { rating: "Mejor valorados", popularity: "Más jugados", winRate: "Más victorias" },
  popularCards: "Cartas populares",
  requireCard: (name) => `Exigir ${name}`,
  filterSearch: "Buscar una carta",
  filterSearchPlaceholder: "Busca cualquier carta…",
  filterRequire: "Exigir",
  filterExclude: "Excluir",
  filterModeGroup: "Tipo de filtro",
  noCardMatches: "Ninguna carta coincide con ese nombre.",
  withCard: (name) => `Con ${name}`,
  withoutCard: (name) => `Sin ${name}`,
  removeFilter: (label) => `Quitar filtro: ${label}`,
  clearFilters: "Quitar filtros",
  resultCount: (matched, total) => `${matched} de ${total} mazos clasificados`,
  advancedSearch: "Búsqueda avanzada con rangos de trofeos y mazos de guerra",
  showMore: "Mostrar más mazos",
  noDecksMatch: "Ningún mazo clasificado contiene todas las cartas exigidas.",
  noDecksMatchHint: "Quita un filtro o cambia al periodo de 7 días para tener una muestra mayor.",
  filterLimit: "Un mazo tiene ocho cartas, así que puedes exigir como máximo ocho.",

  rank: (value) => `#${value}`,
  ratingTitle: "Valoración sobre 100: el límite inferior de Wilson al 95% del porcentaje de victorias (80%) más la popularidad relativa (20%).",
  winRate: "Victorias",
  games: "Partidas",
  usage: "Uso",
  elixir: "Elixir medio",
  evolutions: "Evoluciones",
  copyToGame: "Copiar a Clash Royale",
  copyLink: "Copiar enlace del mazo",
  linkCopied: "Enlace del mazo copiado",
  copyFailed: "El navegador bloqueó la copia; usa Copiar a Clash Royale",
  openBuilder: "Abrir en el creador de mazos",
  builderShort: "Creador",
  matchups: "Cruces",
  hideMatchups: "Ocultar cruces",
  deckLabel: (rank) => `Mazo número ${rank}`,
  bestMatchups: "Mejor contra",
  worstMatchups: "Peor contra",
  matchupsLoading: "Cargando cruces…",
  matchupsNote: (days, minimum) => `Todos los modos, últimos ${days} días, rivales con ${minimum}+ partidas.`,
  matchupsEmpty: (minimum) => `Ningún mazo rival tiene aún ${minimum} partidas contra esta lista.`,
  matchupGames: (games) => `${games} partidas`,
  opponentDeck: "Mazo rival",

  mapTitle: "Mapa del meta",
  mapDek: "Cada carta con suficientes partidas, situada según cuánto se juega y cuánto gana.",
  mapArt: "Arte",
  mapDots: "Puntos",
  mapDisplay: "Estilo de punto",
  mapX: "Uso",
  mapY: "Victorias",
  mapHint: "Selecciona una carta para abrir su informe completo.",
  quadrants: {
    staple: "Básicas del meta",
    gem: "Joyas ocultas",
    overplayed: "Sobreutilizadas",
    struggling: "En apuros"
  },
  quadrantHelp: {
    staple: "Populares y ganadoras",
    gem: "Uso bajo la mediana, pero ganan",
    overplayed: "Populares pero pierden",
    struggling: "Poco jugadas y pierden"
  },
  quadrantEmpty: "Ninguna carta aquí.",
  mapNote: (median) => `Uso dividido en la mediana (${median}); victorias divididas en el 50%.`,
  tierListTitle: "Lista de niveles",
  tierEmpty: "Ninguna carta en este nivel.",
  tierLabel: (tier) => `Nivel ${tier}`,
  towerTitle: "Tropas de Torre",
  towerStarting: "El seguimiento de Tropas de Torre acaba de empezar y no hay historial previo que recuperar. La clasificación aparecerá a medida que se acumulen batallas.",
  towerNote: (count) => `${count} mazos con una Tropa de Torre registrada.`,
  cardLibrary: "Abrir la biblioteca completa de cartas",
  cardTooltipGames: (games) => `${games} partidas`,

  archetypeUsage: "de las partidas",
  archetypeWins: "victorias",
  vsPrevious: (points, days) => `${points} pts frente ${days === 1 ? "al día anterior" : "a la semana anterior"}`,
  changeLabel: (days) => (days === 1 ? "Cambio frente al día anterior" : "Cambio frente a la semana anterior"),
  pointsValue: (points) => `${points} pts`,
  archetypeOpen: "Abrir arquetipo",
  archetypeBack: "Todos los arquetipos",
  archetypeMissing: "Ese arquetipo no existe en este modo y periodo. Elige uno abajo.",
  archetypeDetailDek: (name, games) => `Mazos cuyas dos cartas más distintivas son ${name}. ${games} partidas en este periodo.`,
  archetypeDecks: "Listas más jugadas de este arquetipo",
  trendUsage: "Uso",
  trendWinRate: "Victorias",
  trendMetric: "Métrica de tendencia",
  archetypesEmpty: "Ningún arquetipo supera todavía la muestra mínima en este modo y periodo.",

  aboutData: "Sobre estos datos",
  emptyDecks: "No hay suficientes partidas observadas en este modo y periodo para clasificar mazos.",
  emptyHint: "Prueba el periodo de 7 días o Camino de Leyendas, donde la muestra es mayor.",
  emptyCards: "Ninguna carta supera la muestra mínima en este modo y periodo.",
  emptyMovers: "Ninguna carta superó la muestra mínima en ambos periodos.",
  truncated: "Algunos días alcanzaron el límite de lectura diario, así que estas clasificaciones describen una muestra acotada.",
  deckNote: (total) => `Solo se clasifican mazos vistos al menos cinco veces; esta tabla contiene los ${total} primeros.`,
  tierNote: (floor) => `Las cartas necesitan ${floor}+ partidas. Los niveles dividen la lista ordenada por Wilson: 10% superior S, siguiente 20% A, siguiente 40% B, resto C.`,
  moverNote: (floor, days) => `Cambio de uso frente ${days === 1 ? "al día anterior" : "a la semana anterior"}; las cartas necesitan ${floor}+ partidas en ambos.`,
  archetypeNote: (floor) => `Un arquetipo es el par de cartas menos comunes de un mazo, agrupado automáticamente. Las familias necesitan ${floor}+ partidas.`,
  sourceNote: "Supercell no publica estadísticas del meta. StatsConnect cuenta registros de batalla rastreados y siempre muestra la muestra."
};

const COPY: Record<ReportLocale, MetaCopy> = { en, es };

export type MetaFormat = {
  locale: ReportLocale;
  copy: MetaCopy;
  pct: (value: number, digits?: number) => string;
  pts: (delta: number) => string;
  count: (value: number) => string;
  modeName: (mode: MetaMode) => string;
};

export function useMetaCopy(): MetaFormat {
  const { locale } = useI18n();
  return useMemo(() => ({
    locale,
    copy: COPY[locale],
    pct: (value: number, digits = 1) => formatPercent(value, locale, digits),
    pts: (delta: number) => formatPoints(delta, locale),
    count: (value: number) => formatCount(value, locale),
    modeName: (mode: MetaMode) => COPY[locale].modes[mode]
  }), [locale]);
}
